/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : GPIO1.c
**     Project   : Project_2
**     Processor : MC9S12C128CFU16
**     Component : Init_GPIO
**     Version   : Component 01.100, Driver 01.05, CPU db: 2.87.410
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 13.03.2018, 12:05
**     Abstract  :
**          This file implements the General Purpose Input Output (B)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**
**     Settings  :
**          Component name                                 : GPIO1
**          Device                                         : B
**          Port control                                   : Individual pins
**
**          Used pins                                      :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       0             |  PB0_ADDR0_DATA0
**                       1             |  PB1_ADDR1_DATA1
**                       2             |  PB2_ADDR2_DATA2
**                       3             |  PB3_ADDR3_DATA3
**             ----------------------------------------------------
**
**          Pin0                                           : PB0_ADDR0_DATA0
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin1                                           : PB1_ADDR1_DATA1
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin2                                           : PB2_ADDR2_DATA2
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin3                                           : PB3_ADDR3_DATA3
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Call Init method                               : yes
**     Contents  :
**         Init - void GPIO1_Init(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE GPIO1. */

#include "GPIO1.h"
/*
** ===================================================================
**     Method      :  GPIO1_Init (component Init_GPIO)
**
**     Description :
**         This method initializes registers of the GPIO module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void GPIO1_Init(void)
{
  /* PORTB: BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  clrReg8Bits(PORTB, 0x0FU);            
  /* DDRB: BIT3=1,BIT2=1,BIT1=1,BIT0=1 */
  setReg8Bits(DDRB, 0x0FU);             
}

/* END GPIO1. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
